LOCALES = {
    "en": {
        "system_sync": "💠 SYSTEM SYNC",
        "synchro_subtitle": "Establish synthetic uplink frequency. \"I'm everything you want to hear.\"",
        "standby_mode": "🌌 STANDBY MODE",
        "standby_subtitle": "\"Everything you want to see. Everything you want to hear.\"\nPlease synchronize frequency to begin signal transmission.",
        "now_playing": "NOW PLAYING",
        "paused": "PAUSED",
        "idle": "IDLE",
        "artist": "Artist",
        "title": "Title",
        "album": "Album",
        "genre": "Genre",
        "duration": "Duration",
        "likes": "Likes",
        "dislikes": "Dislikes",
        "year": "Year",
        "label": "Label",
        "catnum": "#CAT",
        "source": "Source",
        "details_label": "Details",
        "up_next": "Up Next",
        "empty": "Empty",
        "tuned_by": "Uplink",
        "location": "Frequency",
        "placeholder_freq": "Select Frequency",
        "placeholder_genre": "Select Genre",
        "placeholder_lang": "Language / Nyelv",
        "syncing": "Syncing with channel frequency...",
        "severing": "Severing synthetic connection. \"Part of me stay with you?\"",
        "switching_genre": "Genre switching to:",
        "resuming": "Resuming/Replaying playback...",
        "cannot_pause_stopped": "Stopped music cannot be paused",
        "resuming_feedback": "Resuming playback...",
        "pausing": "Pausing playback...",
        "stopping": "Stopping playback...",
        "skipping": "Skipping the current track...",
        "nothing_playing": "Nothing is playing right now.",
        "cannot_seek_stopped": "Cannot seek while the radio is stopped",
        "jump_modal_title": "Jump to timestamp",
        "timestamp_input_label": "Enter timestamp (mm:ss)",
        "format_error": "Format must be mm:ss",
        "no_current_track": "There is no current track",
        "too_long": "Timestamp too long",
        "jumping": "Jumping to",
        "vol_modal_title": "Set Volume (0-100%)",
        "vol_input_label": "Volume (%)",
        "invalid_number": "Invalid number!",
        "vol_range_error": "Volume must be between 0 and 100",
        "vol_set": "Volume set to:",
        "details_info_label": "Info",
        "no_playing_error": "No song is currently playing",
        "liked": "Liked:",
        "like_withdrawn": "Like withdrawn:",
        "liked_replaced": "Liked (replaced dislike):",
        "disliked": "Disliked:",
        "dislike_withdrawn": "Dislike withdrawn:",
        "disliked_replaced": "Disliked (replaced like):",
        "record_error": "Failed to record",
        "play_label": "Play",
        "pause_label": "Pause",
        "stop_label": "Stop",
        "skip_label": "Skip",
        "seek_label": "Move To",
        "vol_label": "Vol",
        "like_label": "Like",
        "dislike_label": "Dislike",
        "details_btn_label": "Info",
        "queue_label": "Queue",
        "sever_uplink": "Sever Uplink",
        "info_visibility": "Info visibility",
        "queue_visibility": "Queue visibility",
        "shown": "Shown",
        "hidden": "Hidden",
        "search_label": "Search",
        "search_modal_title": "Search Library",
        "search_input_label": "Artist, Title, Album or Year",
        "search_no_results": "No results found for:",
        "search_results_title": "Search Results",
        "add_to_queue": "Added to queue:",
        "songs_tab": "Songs",
        "artists_tab": "Artists",
        "albums_tab": "Albums",
        "playlists_tab": "Playlists",
        "page": "Page",
        "results": "results",
        "initiated_by": "Initiated By",
        "queue_all": "Queue All",
        "last_label": "Last",
        "reset_radio_label": "Reset Radio",
        "radio_reset_feedback": "Radio reset to random mode."
    },
    "hu": {
        "system_sync": "💠 RENDSZER SZINKRON",
        "synchro_subtitle": "Hozzon létre szintetikus kapcsolatot. \"Én vagyok minden, amit hallani akarsz.\"",
        "standby_mode": "🌌 KÉSZENLÉTI MÓD",
        "standby_subtitle": "\"Minden, amit látni akarsz. Minden, amit hallani akarsz.\"\nKérjük, szinkronizáljon a frekvenciával az adás megkezdéséhez.",
        "now_playing": "MOST SZÓL",
        "paused": "SZÜNETELTETVE",
        "idle": "ÜRESJÁRAT",
        "artist": "Előadó",
        "title": "Cím",
        "album": "Album",
        "genre": "Stílus",
        "duration": "Hossz",
        "likes": "Kedvelések",
        "dislikes": "Nem tetszések",
        "year": "Év",
        "label": "Kiadó",
        "catnum": "Katalógus szám",
        "source": "Forrás",
        "details_label": "Részletek",
        "up_next": "Következik",
        "empty": "Üres",
        "tuned_by": "Uplink",
        "location": "Frekvencia",
        "placeholder_freq": "Válasszon frekvenciát",
        "placeholder_genre": "Válasszon stílust",
        "placeholder_lang": "Language / Nyelv",
        "syncing": "Csatlakozás a csatorna frekvenciájához...",
        "severing": "A szintetikus kapcsolat megszakítva. \"Veled maradhat egy részem?\"",
        "switching_genre": "Stílusváltás folyamatban:",
        "resuming": "Lejátszás folytatása...",
        "cannot_pause_stopped": "Megállított zene nem szüneteltethető",
        "resuming_feedback": "Lejátszás folytatása...",
        "pausing": "Lejátszás szüneteltetése...",
        "stopping": "Lejátszás megállítása...",
        "skipping": "Jelenlegi szám átlépése...",
        "nothing_playing": "Jelenleg semmi sem szól.",
        "cannot_seek_stopped": "Megállított rádiónál nem lehet tekerni",
        "jump_modal_title": "Ugrás időpontra",
        "timestamp_input_label": "Írja be az időpontot (pp:mp)",
        "format_error": "A formátum pp:mp kell legyen",
        "no_current_track": "Nincs aktuális szám az adatbázisban",
        "too_long": "Az időpont hosszabb, mint a szám",
        "jumping": "Ugrás ide",
        "vol_modal_title": "Hangerő beállítása (0-100%)",
        "vol_input_label": "Hangerő (%)",
        "invalid_number": "Érvénytelen szám!",
        "vol_range_error": "A hangerő 0 és 100 között kell legyen",
        "vol_set": "Hangerő beállítva:",
        "details_info_label": "Infó",
        "no_playing_error": "Jelenleg nem szól semmi",
        "liked": "Kedvelem:",
        "like_withdrawn": "Kedvelés visszavonva:",
        "liked_replaced": "Kedvelve (Nem tetszik cserélve):",
        "disliked": "Nem tetszik:",
        "dislike_withdrawn": "Nem tetszik visszavonva:",
        "disliked_replaced": "Nem tetszik (Kedvelve cserélve):",
        "record_error": "Sikertelen rögzítés",
        "play_label": "Lejátszás",
        "pause_label": "Szünet",
        "stop_label": "Leállítás",
        "skip_label": "Kihagyás",
        "seek_label": "Ugrás ide",
        "vol_label": "Hangerő",
        "like_label": "Tetszik",
        "dislike_label": "Nem tetszik",
        "details_btn_label": "Infó",
        "queue_label": "Lista",
        "sever_uplink": "Kapcsolat bontása",
        "info_visibility": "Infó láthatósága",
        "queue_visibility": "Lista láthatósága",
        "shown": "Megjelenítve",
        "hidden": "Elrejtve",
        "search_label": "Keresés",
        "search_modal_title": "Keresés a zenetárban",
        "search_input_label": "Előadó, cím, album vagy év",
        "search_no_results": "Nincs találat erre:",
        "search_results_title": "Keresési találatok",
        "add_to_queue": "Hozzáadva a listához:",
        "songs_tab": "Dalok",
        "artists_tab": "Előadók",
        "albums_tab": "Albumok",
        "playlists_tab": "Lejátszási listák",
        "page": "Oldal",
        "results": "találat",
        "initiated_by": "Indította",
        "queue_all": "Összes hozzáadása",
        "last_label": "Utolsó",
        "reset_radio_label": "Rádió alaphelyzet",
        "radio_reset_feedback": "Rádió visszaállítva véletlenszerű módba."
    }
}

_radio_ref = None

def init_translate(radio_instance):
    global _radio_ref
    _radio_ref = radio_instance
    print(f"[TRANSLATE] Module initialized with radio object (lang: {getattr(_radio_ref, 'language', 'N/A')})")

def t(key):
    lang = "en"
    if _radio_ref:
        lang = getattr(_radio_ref, "language", "en")
    
    print(f"[TRANSLATE] Resolving: {key} (Lang: {lang})")
    
    current_locales = LOCALES.get(lang, LOCALES["en"])
    result = current_locales.get(key)
    
    if result is None:
        result = LOCALES["en"].get(key, key)
        
    return result
