LOCALES = {
    "en": {
        "system_sync": "💠 CONNECTION",
        "synchro_subtitle": "Select a channel to begin transmission.\n\"I'm everything you want to hear.\"",
        "standby_mode": "🌌 STANDBY",
        "standby_subtitle": "\"Everything you want to see. Everything you want to hear.\"\nPlease select a frequency to start the broadcast.",
        "now_playing": "NOW PLAYING",
        "paused": "PAUSED",
        "idle": "IDLE",
        "artist": "Artist",
        "title": "Title",
        "album": "Album",
        "genre": "Genre",
        "duration": "Duration",
        "likes": "Likes",
        "dislikes": "Dislikes",
        "year": "Year",
        "label": "Label",
        "catnum": "#CAT",
        "source": "Source",
        "play_count_label": "Total Plays",
        "last_played_label": "Last Signal",
        "details_label": "Details",
        "history_title": "Playback History",
        "history_label": "History",
        "played_at": "Played at",
        "date_format": "%Y-%m-%d %H:%M",
        "filter_label": "Filter",
        "import_genre_modal_title": "Import Songs from Genre",
        "studio_locked_message": "The Playlist Studio is currently being used by {user}. Please wait until they finish.",
        "filter_modal_title": "Filter by date",
        "filter_from_label": "From (YYYY.MM.DD)",
        "filter_to_label": "To (YYYY.MM.DD)",
        "date_invalid_error": "Invalid date format! Please use YYYY.MM.DD",
        "clear_filter_label": "Clear Filter",
        "delete_history_label": "Delete History",
        "delete_history_confirm": "Are you sure you want to clear all history? This cannot be undone.",
        "history_cleared": "Playback history cleared.",
        "shuffle_label": "Shuffle",
        "full_queue_label": "Full List",
        "remove_song_label": "Remove",
        "shuffle_feedback": "Queue shuffled!",
        "up_next": "Up Next",
        "empty": "Empty",
        "tuned_by": "User",
        "location": "Channel",
        "placeholder_freq": "Select Channel",
        "placeholder_genre": "Select Genre",
        "placeholder_lang": "Language",
        "syncing": "Syncing with channel frequency...",
        "severing": "Severing synthetic connection. \"Part of me stay with you?\"",
        "switching_genre": "Genre switching to:",
        "resuming": "Resuming/Replaying playback...",
        "cannot_pause_stopped": "Stopped music cannot be paused",
        "resuming_feedback": "Resuming playback...",
        "pausing": "Pausing playback...",
        "stopping": "Stopping playback...",
        "forwarding": "Moving to next track...",
        "randomizing": "Generating new signal...",
        "nothing_playing": "Nothing is playing right now.",
        "cannot_seek_stopped": "Cannot seek while the radio is stopped",
        "back_error": "No more history to go back to!",
        "cooldown_error": "System stable, please wait a moment...",
        "jump_modal_title": "Jump to timestamp",
        "timestamp_input_label": "Enter timestamp (mm:ss)",
        "format_error": "Format must be mm:ss",
        "no_current_track": "There is no current track",
        "too_long": "Timestamp too long",
        "jumping": "Jumping to",
        "vol_modal_title": "Set Volume (0-100%)",
        "vol_input_label": "Volume (%)",
        "invalid_number": "Invalid number!",
        "vol_range_error": "Volume must be between 0 and 100",
        "vol_set": "Volume set to:",
        "no_playing_error": "No song is currently playing",
        "liked": "Liked:",
        "like_withdrawn": "Like withdrawn:",
        "liked_replaced": "Liked (replaced dislike):",
        "disliked": "Disliked:",
        "dislike_withdrawn": "Dislike withdrawn:",
        "disliked_replaced": "Disliked (replaced like):",
        "record_error": "Failed to record",
        "play_label": "Play",
        "pause_label": "Pause",
        "stop_label": "Stop",
        "forward_label": "Forward",
        "random_label": "Random",
        "seek_label": "Move To",
        "back_label": "Back",
        "vol_label": "Vol",
        "like_label": "Like",
        "dislike_label": "Dislike",
        "details_btn_label": "Info",
        "queue_label": "Queue",
        "sever_uplink": "Disconnect",
        "info_visibility": "Info visibility",
        "queue_visibility": "Queue visibility",
        "shown": "Shown",
        "hidden": "Hidden",
        "search_label": "Search",
        "search_modal_title": "Search Library",
        "search_input_label": "Artist, Title, Album or Year",
        "search_no_results": "No results found for:",
        "add_to_queue": "Added to queue:",
        "songs_tab": "Songs",
        "artists_tab": "Artists",
        "albums_tab": "Albums",
        "playlists_tab": "Playlists",
        "page": "Page",
        "songs": "songs",
        "results": "results",
        "initiated_by": "User:",
        "queue_all": "Queue All",
        "last_label": "Last",
        "reset_radio_label": "Reset Radio",
        "radio_reset_feedback": "Radio reset to random mode.",
        "no_permission": "You do not have the required role to access this channel.",
        "playlist_studio_label": "Playlist Studio",
        "playlist_studio_title": "🔧 PLAYLIST STUDIO",
        "playlist_studio_subtitle": "Create and manage your custom playlists.",
        "new_playlist_label": "New Playlist",
        "delete_playlist_label": "Delete Playlist",
        "select_playlist_placeholder": "Select Playlist to Edit",
        "playlist_editor_title": "📝 EDITING PLAYLIST",
        "save_exit_label": "Save & Exit",
        "create_playlist_modal_title": "Create New Playlist",
        "playlist_name_label": "Playlist Name",
        "song_added_to_playlist": "Added to playlist:",
        "song_removed_from_playlist": "Removed from playlist:",
        "playlist_deleted": "Playlist deleted.",
        "rename_playlist_label": "Rename",
        "rename_playlist_modal_title": "Rename Playlist"
    },
    "hu": {
        "system_sync": "💠 CSATLAKOZÁS",
        "synchro_subtitle": "Válasszon csatornát az adás megkezdéséhez.\n\"Én vagyok minden, amit hallani akarsz.\"",
        "standby_mode": "🌌 KÉSZENLÉT",
        "standby_subtitle": "\"Minden, amit látni akarsz. Minden, amit hallani akarsz.\"\nVálasszon csatornát a sugárzás indításához.",
        "now_playing": "MOST SZÓL",
        "paused": "SZÜNETELTETVE",
        "idle": "ÜRESJÁRAT",
        "artist": "Előadó",
        "title": "Cím",
        "album": "Album",
        "genre": "Stílus",
        "duration": "Hossz",
        "likes": "Kedvelések",
        "dislikes": "Nem tetszések",
        "year": "Év",
        "label": "Kiadó",
        "catnum": "Katalógus szám",
        "source": "Forrás",
        "play_count_label": "Összes lejátszás",
        "last_played_label": "Utolsó adás",
        "details_label": "Részletek",
        "history_title": "Lejátszási előzmények",
        "history_label": "Előzmények",
        "played_at": "Lejátszva:",
        "date_format": "%Y.%m.%d %H:%M",
        "filter_label": "Szűrő",
        "filter_modal_title": "Szűrés dátum alapján",
        "filter_from_label": "Ettől (ÉÉÉÉ.HH.NN)",
        "filter_to_label": "Eddig (ÉÉÉÉ.HH.NN)",
        "date_invalid_error": "Hibás dátum formátum! Használja: ÉÉÉÉ.HH.NN",
        "clear_filter_label": "Szűrő törlése",
        "delete_history_label": "Előzmények törlése",
        "delete_history_confirm": "Biztosan törölni szeretnél minden előzményt? Ez nem vonható vissza.",
        "history_cleared": "Lejátszási előzmények törölve.",
        "shuffle_label": "Keverés",
        "full_queue_label": "Teljes lista",
        "remove_song_label": "Eltávolítás",
        "shuffle_feedback": "Várólista megkeverve!",
        "up_next": "Következik",
        "empty": "Üres",
        "tuned_by": "Felhasználó",
        "location": "Csatorna",
        "placeholder_freq": "Csatorna kiválasztása",
        "placeholder_genre": "Stílus kiválasztása",
        "placeholder_lang": "Nyelvválasztás",
        "syncing": "Csatlakozás a csatorna frekvenciájához...",
        "severing": "A szintetikus kapcsolat megszakítva. \"Veled maradhat egy részem?\"",
        "switching_genre": "Stílusváltás folyamatban:",
        "resuming": "Lejátszás folytatása...",
        "cannot_pause_stopped": "Megállított zene nem szüneteltethető",
        "resuming_feedback": "Lejátszás folytatása...",
        "pausing": "Lejátszás szüneteltetése...",
        "stopping": "Lejátszás leállítása...",
        "forwarding": "Ugrás a következő számra...",
        "randomizing": "Új jel generálása...",
        "nothing_playing": "Jelenleg semmi sem szól.",
        "cannot_seek_stopped": "Megállított rádiónál nem lehet tekerni",
        "back_error": "Nincs több előzmény a visszafelé léptetéshez!",
        "cooldown_error": "Rendszer stabilizálása folyamatban, várjon egy pillanatot...",
        "jump_modal_title": "Ugrás időpontra",
        "timestamp_input_label": "Írja be az időpontot (pp:mp)",
        "format_error": "A formátum pp:mp kell legyen",
        "no_current_track": "Nincs aktuális szám az adatbázisban",
        "too_long": "Az időpont hosszabb, mint a szám",
        "jumping": "Ugrás ide",
        "vol_modal_title": "Hangerő beállítása (0-100%)",
        "vol_input_label": "Hangerő (%)",
        "invalid_number": "Érvénytelen szám!",
        "vol_range_error": "A hangerő 0 és 100 között kell legyen",
        "vol_set": "Hangerő beállítva:",
        "no_playing_error": "Jelenleg nem szól semmi",
        "liked": "Kedvelem:",
        "like_withdrawn": "Kedvelés visszavonva:",
        "liked_replaced": "Kedvelve (Nem tetszik cserélve):",
        "disliked": "Nem tetszik:",
        "dislike_withdrawn": "Nem tetszik visszavonva:",
        "disliked_replaced": "Nem tetszik (Kedvelve cserélve):",
        "record_error": "Sikertelen rögzítés",
        "play_label": "Lejátszás",
        "pause_label": "Szünet",
        "stop_label": "Leállítás",
        "forward_label": "Előre",
        "random_label": "Random",
        "seek_label": "Ugrás ide",
        "back_label": "Vissza",
        "vol_label": "Hangerő",
        "like_label": "Tetszik",
        "dislike_label": "Nem tetszik",
        "details_btn_label": "Infó",
        "queue_label": "Lista",
        "sever_uplink": "Lecsatlakozás",
        "info_visibility": "Infó láthatósága",
        "queue_visibility": "Lista láthatósága",
        "shown": "Megjelenítve",
        "hidden": "Elrejtve",
        "search_label": "Keresés",
        "search_modal_title": "Keresés a zenetárban",
        "search_input_label": "Előadó, cím, album vagy év",
        "search_no_results": "Nincs találat erre:",
        "add_to_queue": "Hozzáadva a listához:",
        "songs_tab": "Dalok",
        "artists_tab": "Előadók",
        "albums_tab": "Albumok",
        "playlists_tab": "Lejátszási listák",
        "page": "Oldal",
        "songs": "dal",
        "results": "találat",
        "initiated_by": "Felhasználó:",
        "queue_all": "Összes hozzáadása",
        "last_label": "Utolsó",
        "reset_radio_label": "Rádió alaphelyzet",
        "radio_reset_feedback": "Rádió visszaállítva véletlenszerű módba.",
        "no_permission": "Nincs jogosultsága ehhez a csatornához a szükséges rang hiánya miatt.",
        "playlist_studio_label": "Playlist Stúdió",
        "playlist_studio_title": "🔧 PLAYLIST STÚDIÓ",
        "playlist_studio_subtitle": "Saját lejátszási listák kezelése és létrehozása.",
        "new_playlist_label": "Új lista",
        "delete_playlist_label": "Lista törlése",
        "select_playlist_placeholder": "Lista kiválasztása szerkesztésre",
        "playlist_editor_title": "📝 LISTA SZERKESZTÉSE",
        "save_exit_label": "Mentés és kilépés",
        "create_playlist_modal_title": "Új lejátszási lista létrehozása",
        "playlist_name_label": "Lista neve",
        "song_added_to_playlist": "Hozzáadva a listához:",
        "song_removed_from_playlist": "Eltávolítva a listáról:",
        "playlist_deleted": "Lejátszási lista törölve.",
        "rename_playlist_label": "Átnevezés",
        "import_genre_modal_title": "Dalok importálása műfajból",
        "studio_locked_message": "A Playlist Stúdiót jelenleg {user} használja. Kérlek várd meg, amíg befejezi."
    }
}

_radio_ref = None

def init_translate(radio_instance):
    global _radio_ref
    _radio_ref = radio_instance
    print(f"[TRANSLATE] Module initialized with radio object (lang: {getattr(_radio_ref, 'language', 'N/A')})")

def t(key):
    lang = "en"
    if _radio_ref:
        lang = getattr(_radio_ref, "language", "en")
    
    print(f"[TRANSLATE] Resolving: {key} (Lang: {lang})")
    
    current_locales = LOCALES.get(lang, LOCALES["en"])
    result = current_locales.get(key)
    
    if result is None:
        result = LOCALES["en"].get(key, key)
        
    return result
