from ui_icons import Icons
LOCALES = {
    "en": {
        "system_sync": f"{Icons.SYNC} CONNECTION",
        "synchro_subtitle": "Pick a channel to start the transmission.\n\"I'm everything you want to hear.\"",
        "standby_mode": f"{Icons.STANDBY} STANDBY",
        "standby_subtitle": "\"Everything you want to see. Everything you want to hear.\"\nPick a channel to start the broadcast.",
        "now_playing": "NOW PLAYING",
        "paused": "PAUSED",
        "idle": "IDLE",
        "presence_listening": "Listening to",
        "presence_paused": "Paused",
        "artist": "Artist",
        "title": "Title",
        "album": "Album",
        "genre": "Genre",
        "duration": "Duration",
        "likes": "Likes",
        "dislikes": "Dislikes",
        "year": "Year",
        "label": "Label",
        "catnum": "#CAT",
        "source": "Source",
        "play_count_label": "Total Plays",
        "last_played_label": "Last Signal",
        "details_label": "Details",
        "history_title": "Playback History",
        "history_label": "History",
        "stats_label": "Stats",
        "stats_title": f"{Icons.STATS} ANALYTICS",
        "stats_weekly": "Weekly",
        "stats_monthly": "Monthly",
        "stats_all_time": "All Time",
        "top_artists": "Top 5 Artists",
        "top_songs": "Top 5 Tracks",
        "top_listeners": "Most Active Listeners",
        "played_at": "Played at",
        "date_format": "%Y-%m-%d %H:%M",
        "filter_label": "Filter",
        "studio_locked_message": "{user} is using the Playlist Studio right now. Hold on until they're done.",
        "filter_modal_title": "Filter by date",
        "filter_from_label": "From (YYYY.MM.DD)",
        "filter_to_label": "To (YYYY.MM.DD)",
        "date_invalid_error": "Wrong date format! Use YYYY.MM.DD",
        "clear_filter_label": "Clear Filter",
        "delete_history_label": "Delete History",
        "delete_history_confirm": "Sure you want to clear all history? You can't undo this.",
        "history_cleared": "Playback history cleared.",
        "shuffle_label": "Shuffle",
        "edit_queue_label": "Edit Queue",
        "clear_queue_label": "Clear Queue",
        "clear_queue_confirm": "Sure you want to clear the whole queue?",
        "remove_song_label": "Remove",
        "shuffle_feedback": "Queue shuffled!",
        "up_next": "Up Next",
        "empty": "Empty",
        "tuned_by": "User",
        "location": "Channel",
        "placeholder_freq": "Pick a Channel",
        "placeholder_genre": "Pick a Genre",
        "placeholder_lang": "Language",
        "placeholder_ui": "Pick a UI Style",
        "syncing": "Syncing with channel frequency...",
        "severing": "Severing synthetic connection. \"Part of me stay with you?\"",
        "switching_genre": "Switching genre to:",
        "resuming": "Resuming playback...",
        "cannot_pause_stopped": "Can't pause music while it's stopped",
        "resuming_feedback": "Getting back to the music...",
        "pausing": "Pausing playback...",
        "stopping": "Stopping playback...",
        "forwarding": "Moving to next track...",
        "randomizing": "Generating new signal...",
        "nothing_playing": "Nothing's playing right now.",
        "cannot_seek_stopped": "Can't seek while the radio is stopped",
        "back_error": "Nothing left in history to go back to!",
        "cooldown_error": "System's stabilizing, hold on a sec...",
        "jump_modal_title": "Jump to timestamp",
        "timestamp_input_label": "Enter timestamp (mm:ss)",
        "format_error": "Format's gotta be mm:ss",
        "no_current_track": "There's no current track",
        "too_long": "Timestamp's too long",
        "jumping": "Jumping to",
        "vol_modal_title": "Set Volume (0-100%)",
        "vol_input_label": "Volume (%)",
        "invalid_number": "That's not a number!",
        "vol_range_error": "Volume's gotta be between 0 and 100",
        "vol_set": "Volume set to:",
        "no_playing_error": "Nothing's playing right now",
        "liked": "Liked:",
        "like_withdrawn": "Like withdrawn:",
        "liked_replaced": "Liked (replaced dislike):",
        "disliked": "Disliked:",
        "dislike_withdrawn": "Dislike withdrawn:",
        "disliked_replaced": "Disliked (replaced like):",
        "record_error": "Failed to record",
        "play_label": "Play",
        "pause_label": "Pause",
        "stop_label": "Stop",
        "forward_label": "Forward",
        "random_label": "Random",
        "seek_label": "Seek",
        "back_label": "Back",
        "vol_label": "Volume",
        "like_label": "Like",
        "dislike_label": "Dislike",
        "details_btn_label": "Info",
        "queue_label": "Queue",
        "sever_uplink": "Disconnect",
        "info_visibility": "Info visibility",
        "queue_visibility": "Queue visibility",
        "shown": "Shown",
        "hidden": "Hidden",
        "search_label": "Search",
        "library_label": "Library",
        "search_modal_title": "Search Library",
        "search_input_label": "Artist, Title, Album or Year",
        "search_no_results": "No results found for:",
        "add_to_queue": "Added to queue:",
        "songs_tab": "Songs",
        "artists_tab": "Artists",
        "albums_tab": "Albums",
        "playlists_tab": "Playlists",
        "page": "Page",
        "songs": "songs",
        "results": "results",
        "initiated_by": "User:",
        "queue_all": "Queue All",
        "add_all": "Add All",
        "bulk_added_to_playlist": "Added {count} songs to playlist.",
        "bulk_added_to_queue": "Added {count} songs to queue.",
        "last_label": "Last",
        "reset_radio_label": "Reset Radio",
        "radio_reset_feedback": "Radio's back to random mode.",
        "no_permission": "You don't have the right role for this channel.",
        "no_permission_general": "You don't have permission for that.",
        "playlist_studio_label": "Playlist Studio",
        "playlist_studio_title": f"{Icons.STUDIO} PLAYLIST STUDIO",
        "playlist_studio_subtitle": "Manage and edit your playlists here.",
        "new_playlist_label": "New Playlist",
        "delete_playlist_label": "Delete Playlist",
        "select_playlist_placeholder": "Pick a playlist to edit",
        "playlist_editor_title": f"{Icons.PLAYLIST} EDITING PLAYLIST",
        "save_exit_label": "Save & Exit",
        "create_playlist_modal_title": "Create New Playlist",
        "playlist_name_label": "Playlist Name",
        "song_added_to_playlist": "Added to playlist:",
        "song_removed_from_playlist": "Removed from playlist:",
        "playlist_deleted": "Playlist deleted.",
        "rename_playlist_label": "Rename",
        "rename_playlist_modal_title": "Rename Playlist",
        "ui_mode_label": "Interface Style",
        "ui_mode_full": "Full Interface (Icons + Labels)",
        "ui_mode_compact": "Compact Interface (Icons only)",
        "rescan_label": "Rescan Library",
        "rescanning": "Scanning the library... Hold on.",
        "rescan_complete": "Scan's done! Found {inserted} new tracks, skipped {skipped}.",
        "feedback_label": "Feedback",
        "feedback_modal_title": "Send Feedback",
        "feedback_type_label": "Type",
        "feedback_type_bug": "Bug Report",
        "feedback_type_feature": "Feature Request",
        "feedback_type_music": "Music Request",
        "feedback_content_label": "Tell us more...",
        "feedback_music_content_label": "Artist - Title (and link if possible)",
        "feedback_sent": "Feedback received. Transmission complete.",
        "added_to_favs": "Added to favourites:",
        "removed_from_favs": "Removed from favourites:",
        "fav_add_label": "Favorite",
        "fav_rem_label": "Unfavorite"
    },
    "hu": {
        "system_sync": f"{Icons.SYNC} CSATLAKOZÁS",
        "synchro_subtitle": "Válassz csatornát az adás megkezdéséhez.\n\"Én vagyok minden, amit hallani akarsz.\"",
        "standby_mode": f"{Icons.STANDBY} KÉSZENLÉT",
        "standby_subtitle": "\"Minden, amit látni akarsz. Minden, amit hallani akarsz.\"\nVálassz csatornát a sugárzás indításához.",
        "now_playing": "MOST SZÓL",
        "paused": "SZÜNETELTETVE",
        "idle": "ÜRESJÁRAT",
        "presence_listening": "Hallgatja:",
        "presence_paused": "Szüneteltetve",
        "artist": "Előadó",
        "title": "Cím",
        "album": "Album",
        "genre": "Stílus",
        "duration": "Hossz",
        "likes": "Kedvelések",
        "dislikes": "Nem tetszések",
        "year": "Év",
        "label": "Kiadó",
        "catnum": "Katalógus szám",
        "source": "Forrás",
        "play_count_label": "Összes lejátszás",
        "last_played_label": "Utolsó adás",
        "details_label": "Részletek",
        "history_title": "Lejátszási előzmények",
        "history_label": "Előzmények",
        "stats_label": "Statisztika",
        "stats_title": f"{Icons.STATS} ANALITIKA",
        "stats_weekly": "Heti",
        "stats_monthly": "Havi",
        "stats_all_time": "Összesített",
        "top_artists": "Top 5 Előadó",
        "top_songs": "Top 5 Zeneszám",
        "top_listeners": "Legaktívabb Hallgatók",
        "played_at": "Lejátszva:",
        "date_format": "%Y.%m.%d %H:%M",
        "filter_label": "Szűrő",
        "filter_modal_title": "Szűrés dátum alapján",
        "filter_from_label": "Ettől (ÉÉÉÉ.HH.NN)",
        "filter_to_label": "Eddig (ÉÉÉÉ.HH.NN)",
        "date_invalid_error": "Hibás dátum formátum! Használd: ÉÉÉÉ.HH.NN",
        "clear_filter_label": "Szűrő törlése",
        "delete_history_label": "Előzmények törlése",
        "delete_history_confirm": "Biztosan törölni szeretnél minden előzményt? Ez nem vonható vissza.",
        "history_cleared": "Lejátszási előzmények törölve.",
        "shuffle_label": "Keverés",
        "edit_queue_label": "Várólista szerkesztése",
        "clear_queue_label": "Várólista ürítése",
        "clear_queue_confirm": "Biztosan törölni szeretnéd a teljes várólistát?",
        "remove_song_label": "Eltávolítás",
        "shuffle_feedback": "Várólista megkeverve!",
        "up_next": "Következik",
        "empty": "Üres",
        "tuned_by": "Felhasználó",
        "location": "Csatorna",
        "placeholder_freq": "Válassz csatornát",
        "placeholder_genre": "Válassz stílust",
        "placeholder_lang": "Nyelvválasztás",
        "placeholder_ui": "Kezelőfelület stílusa",
        "syncing": "Csatlakozás a csatorna frekvenciájához...",
        "severing": "A szintetikus kapcsolat megszakítva. \"Veled maradhat egy részem?\"",
        "switching_genre": "Stílusváltás folyamatban:",
        "resuming": "Lejátszás folytatása...",
        "cannot_pause_stopped": "A megállított zenét nem tudod szüneteltetni",
        "resuming_feedback": "Lejátszás folytatása...",
        "pausing": "Lejátszás szüneteltetése...",
        "stopping": "Lejátszás leállítása...",
        "forwarding": "Ugrás a következő számra...",
        "randomizing": "Új jel generálása...",
        "nothing_playing": "Jelenleg semmi sem szól.",
        "cannot_seek_stopped": "Megállított rádiónál nem tudsz tekerni",
        "back_error": "Nincs több előzmény, amin visszaléphetnél!",
        "cooldown_error": "Rendszer stabilizálása folyamatban, várj egy pillanatot...",
        "jump_modal_title": "Ugrás időpontra",
        "timestamp_input_label": "Add meg az időpontot (pp:mp)",
        "format_error": "A formátum pp:mp kell, hogy legyen",
        "no_current_track": "Nincs aktuális szám az adatbázisban",
        "too_long": "Az időpont hosszabb, mint a szám",
        "jumping": "Ugrás ide",
        "vol_modal_title": "Hangerő beállítása (0-100%)",
        "vol_input_label": "Hangerő (%)",
        "invalid_number": "Érvénytelen szám!",
        "vol_range_error": "A hangerőnek 0 és 100 között kell lennie",
        "vol_set": "Hangerő beállítva:",
        "no_playing_error": "Jelenleg nem szól semmi",
        "liked": "Kedvelem:",
        "like_withdrawn": "Kedvelés visszavonva:",
        "liked_replaced": "Kedvelve (Nem tetszik lecserélve):",
        "disliked": "Nem tetszik:",
        "dislike_withdrawn": "Nem tetszik visszavonva:",
        "disliked_replaced": "Nem tetszik (Kedvelés lecserélve):",
        "record_error": "Sikertelen rögzítés",
        "play_label": "Lejátszás",
        "pause_label": "Szünet",
        "stop_label": "Leállítás",
        "forward_label": "Előre",
        "random_label": "Random",
        "seek_label": "Tekerés",
        "back_label": "Vissza",
        "vol_label": "Hangerő",
        "like_label": "Tetszik",
        "dislike_label": "Nem tetszik",
        "details_btn_label": "Infó",
        "queue_label": "Lista",
        "sever_uplink": "Lecsatlakozás",
        "info_visibility": "Infó láthatósága",
        "queue_visibility": "Lista láthatósága",
        "shown": "Megjelenítve",
        "hidden": "Elrejtve",
        "search_label": "Keresés",
        "library_label": "Médiatár",
        "search_modal_title": "Keresés a zenetárban",
        "search_input_label": "Előadó, cím, album vagy év",
        "search_no_results": "Nincs találat erre:",
        "add_to_queue": "Hozzáadva a listához:",
        "songs_tab": "Dalok",
        "artists_tab": "Előadók",
        "albums_tab": "Albumok",
        "playlists_tab": "Lejátszási listák",
        "page": "Oldal",
        "songs": "dal",
        "results": "találat",
        "initiated_by": "Felhasználó:",
        "queue_all": "Összes hozzáadása",
        "add_all": "Összes hozzáadása",
        "bulk_added_to_playlist": "{count} dal hozzáadva a playlisthez.",
        "bulk_added_to_queue": "{count} dal hozzáadva a várólistához.",
        "last_label": "Utolsó",
        "reset_radio_label": "Rádió alaphelyzet",
        "radio_reset_feedback": "Rádió visszaállítva véletlenszerű módba.",
        "no_permission": "Nincs jogosultságod ehhez a csatornához a szükséges rang hiánya miatt.",
        "no_permission_general": "Nincs jogosultságod ehhez a művelethez.",
        "playlist_studio_label": "Playlist Stúdió",
        "playlist_studio_title": f"{Icons.STUDIO} PLAYLIST STÚDIÓ",
        "playlist_studio_subtitle": "Saját létrehozott listáid kezelése és szerkesztése.",
        "new_playlist_label": "Új lista",
        "delete_playlist_label": "Lista törlése",
        "select_playlist_placeholder": "Válassz listát a szerkesztéshez",
        "playlist_editor_title": f"{Icons.PLAYLIST} LISTA SZERKESZTÉSE",
        "save_exit_label": "Mentés és kilépés",
        "create_playlist_modal_title": "Új lejátszási lista létrehozása",
        "playlist_name_label": "Lista neve",
        "song_added_to_playlist": "Hozzáadva a listához:",
        "song_removed_from_playlist": "Eltávolítva a listáról:",
        "playlist_deleted": "Lejátszási lista törölve.",
        "rename_playlist_label": "Átnevezés",
        "studio_locked_message": "A Playlist Stúdiót jelenleg {user} használja. Kérlek várd meg, amíg befejezi.",
        "ui_mode_label": "Kezelőfelület stílusa",
        "ui_mode_full": "Teljes felület (Ikonok + Szöveg)",
        "ui_mode_compact": "Kompakt felület (Csak ikonok)",
        "rescan_label": "Zenetár Újraszkennelése",
        "rescanning": "Zenetár szkennelése... Kérlek várj.",
        "rescan_complete": "Szkennelés kész! {inserted} új dal hozzáadva, {skipped} kihagyva.",
        "feedback_label": "Visszajelzés",
        "feedback_modal_title": "Visszajelzés küldése",
        "feedback_type_label": "Típus",
        "feedback_type_bug": "Hiba jelentése",
        "feedback_type_feature": "Ötlet beküldése",
        "feedback_type_music": "Zene kérése",
        "feedback_content_label": "Részletek...",
        "feedback_music_content_label": "Előadó - Cím (és link ha van)",
        "feedback_sent": "Visszajelzés fogadva. Adatátvitel kész.",
        "added_to_favs": "Hozzáadva a kedvencekhez:",
        "removed_from_favs": "Eltávolítva a kedvencekből:",
        "fav_add_label": "Kedvenc",
        "fav_rem_label": "Mégsem"
    }
}
_radio_ref = None

def init_translate(radio_instance):
    global _radio_ref
    _radio_ref = radio_instance

def t(key):
    lang = "en"
    if _radio_ref:
        lang = getattr(_radio_ref, "language", "en")
    current_locales = LOCALES.get(lang, LOCALES["en"])
    result = current_locales.get(key)
    if result is None:
        result = LOCALES["en"].get(key, key)
    return result
